Repository loot/fallout3, pull requests merged in 2021-03, with the labels that each got.

#193 Remove extra newlines
  masterlist.yaml
Labels: correction

#197 Inline single-entry lists
  masterlist.yaml
Labels: refactoring

#199 Replace &requiresFOSE
  masterlist.yaml
Labels: refactoring

#200 Add Simplified Chinese &quickClean translation
  masterlist.yaml
Labels: localization

#202 Update NVAC global message
  masterlist.yaml
Labels: refactoring

#204 Update Flashlight
  masterlist.yaml
Labels: refactoring

#208 Add Bulgarian localization
  masterlist.yaml
Labels: localization

#212 Update Bulgarian localization
  masterlist.yaml
Labels: localization

#216 Update Korean localization
  masterlist.yaml
Labels: localization

#217 Update aliased messages
  masterlist.yaml
Labels: correction

#218 Update FOSE Plugin Requirements message
  masterlist.yaml
Labels: correction

#219 Update Korean localization
  masterlist.yaml
Labels: localization

#226 Update Clarity
  masterlist.yaml
Labels: correction

#227 Add Italian localization
  masterlist.yaml
Labels: localization

#229 Correct Portuguese locale codes
  masterlist.yaml
Labels: correction
